---

- hosts: all
  become: yes
  tasks:
    - name: update
      apt:
        name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: install some required packages
      apt:
        name={{item}} state=latest update_cache=yes force_apt_get=yes
      loop: ['vim','python3-pip','apt-transport-https','curl','software-properties-common','virtualenv','python3-setuptools','git']
      
- name: Database Installation
  hosts: host3
  become: yes
  tasks:
    - name: download postgres
      apt: 
        name: postgresql
        update-cache: yes
      tags:
        - database
    - name: start postgres
      service:
        name: postgresql
        state: started
        enabled: yes
      tags:
        - database

    - name: get current ip address
      vars:
        hostip: "{{ansible_eth1.ipv4.address }}"
      tags:
        - database

- name: webserver installation 
  hosts: host2
  tasks:
    - name: Run whoami without become.
      command: whoami
      changed_when: false
      become: false
      register: whoami
      tags:
        - web

    - name: Delete content & directory
      file:
        state: absent
        path: "/home/{{ whoami.stdout }}/CloudManagement"

    - name: Install nginx
      become: yes
      apt:
        name=nginx state=latest update_cache=yes force_apt_get=yes
      tags:
        - web

    - name: install postgres connection library
      become: yes
      apt:
        name=libpq-dev state=latest force_apt_get=yes
      tags:
        - web

    - name: start nginx
      become: yes
      service:
        name: nginx
        state: started
        enabled: yes
      tags:
        - web

    - name: clone django project from github
      git:
        repo: https://github.com/rection/Cloud-Management-Panel.git
        clone: yes
        dest: "/home/{{ whoami.stdout }}/CloudManagement"
      tags:
        - web

    - name: Install requried extensions
      pip:
        requirements: "/home/{{ whoami.stdout }}/CloudManagement/requirements.txt"
        virtualenv: "/home/{{ whoami.stdout }}/CloudManagement/myenv"
        virtualenv_python: python3.9
      tags:
        - web

    - name: replace database host 
      replace:
        path: "/home/{{ whoami.stdout }}/CloudManagement/cloudpanel/settings.py"
        regexp: 'localhost'
        replace: hostip
      tags:
        - web

    - name: replace database port
      replace:
        path: "/home/{{ whoami.stdout }}/CloudManagement/cloudpanel/settings.py"
        regexp: '32450'
        replace: '5432'
      tags:
        - web 





