---

- hosts: all
  become: yes
  tasks:
    - name: update
      apt:
        name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: install some required packages
      apt:
        name={{item}} state=latest update_cache=yes force_apt_get=yes
      loop: ['vim','python3-pip','apt-transport-https','curl','wget','software-properties-common','virtualenv','python3-setuptools']

- name: webserver installation 
  hosts: host2
  become: yes
  tasks:
    - name: Install nginx
      apt:
        name=nginx state=latest update_cache=yes force_apt_get=yes
      tags:
        - web

    - name: start nginx
      service:
        name: nginx
        state: started
        enabled: yes
      tags:
        - web

  

- name: Database Installation
  hosts: host3
  become: yes
  tasks:
    - name: download postgres
      apt: 
        name: postgresql
        update-cache: yes
      tags:
        - database
    - name: start postgres
      service:
        name: postgresql
        state: started
        enabled: yes
      tags:
        - database




