---

- hosts: all
  become: yes
  tasks:
    - name: update
      apt:
        name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: install some required packages
      apt:
        name={{item}} state=latest update_cache=yes force_apt_get=yes
      loop: ['vim','python3-pip','apt-transport-https','curl','software-properties-common','virtualenv','python3-setuptools','git']

- name: webserver installation 
  hosts: host2
  tasks:

    - name: Install nginx
      become: yes
      apt:
        name=nginx state=latest update_cache=yes force_apt_get=yes
      tags:
        - web

    - name: install postgres connection library
      become: yes
      apt:
        name=libpq-dev state=latest force_apt_get=yes
      tags:
        - web

    - name: start nginx
      become: yes
      service:
        name: nginx
        state: started
        enabled: yes
      tags:
        - web

    - name: clone django project from github
      git:
        repo: https://github.com/rection/Cloud-Management-Panel.git
        clone: no
        dest: /home/vagrant/CloudManagement
      tags:
        - web

    - name: Install requried extensions
      pip:
        requirements: /home/vagrant/CloudManagement/requirements.txt
        virtualenv: /home/vagrant/CloudManagement/myenv
        virtualenv_python: python3.9
      tags:
        - web

- name: Database Installation
  hosts: host3
  become: yes
  tasks:
    - name: download postgres
      apt: 
        name: postgresql
        update-cache: yes
      tags:
        - database
    - name: start postgres
      service:
        name: postgresql
        state: started
        enabled: yes
      tags:
        - database




