version: '2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.1
    environment:
      SERVER_NAME: kibana.safabayar.org
      ELASTICSEARCH_HOSTS: http://elasticsearch.safabayar.org
